version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
      - SRC_HOME=$PWD
  pre_build:
    commands:
      - cd $SRC_HOME
      - cd functions
      - lein test
  build:
    commands:
      - cd $SRC_HOME
      - echo Build started on `date`
      - cd functions
      - lein uberjar
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - functions/target/uberjar/wort-0.1.0-SNAPSHOT-standalone.jar
