AWSTemplateFormatVersion: 2010-09-09
Description: Lambda and API Gateway
Parameters:
  LambdaSourceBucket:
    Description: The name of the S3 bucket that contains the source code of your Lambda
      function.
    Type: String
  LambdaJarKey:
    Description: The location and name of your source code .jar file.
    Type: String
    Default: lambda.jar
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: logs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
  PhraseBuildingLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: LambdaSourceBucket
        S3Key:
          Ref: LambdaJarKey
      Description: Frontend handler
      Handler: wort.core.PhraseBuilder
      MemorySize: 512
      Role:
        Fn::GetAtt:
        - LambdaRole
        - Arn
      Runtime: java8
      Timeout: 15 # seconds
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName:
        Fn::GetAtt:
        - PhraseBuildingLambda
        - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:aws:execute-api:'
          - Ref: AWS::Region
          - ":"
          - Ref: AWS::AccountId
          - ":"
          - Ref: PhraseBuildingRestApi
          - "/*"
  PhraseBuildingRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${AWS::StackName}
  PhraseBuildingModel:
    Type: AWS::ApiGateway::Model
    Properties:
      ContentType: application/json
      Name: PhraseBuilding
      RestApiId:
        Ref: PhraseBuildingRestApi
      Schema:
        "$schema": http://json-schema.org/draft-04/schema#
        title: PhraseBuilding
        type: object
        additionalProperties: false
        properties:
          phrase:
            type: string
        required:
        - phrase
  PhraseBuildingResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId:
        Ref: PhraseBuildingRestApi
      ParentId:
        Fn::GetAtt:
        - PhraseBuildingRestApi
        - RootResourceId
      PathPart: sound_concatenation
  PhraseBuildingGet:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:
        Ref: PhraseBuildingRestApi
      ResourceId:
        Ref: PhraseBuildingResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri:
          Fn::Join:
          - ''
          - - 'arn:aws:apigateway:'
            - Ref: AWS::Region
            - ":lambda:path/2015-03-31/functions/"
            - Fn::GetAtt:
              - PhraseBuildingLambda
              - Arn
            - "/invocations"
        IntegrationResponses:
        - ResponseTemplates:
            application/json: "{\"phrase\": \"$input.body\"}"
          StatusCode: 200
        PassthroughBehavior: NEVER
        RequestTemplates:
          application/json: |
            "{\"phrase\": \"$input.params('phrase')\"}"
      RequestParameters:
        method.request.querystring.phrase: true
      MethodResponses:
      - ResponseModels:
          application/json:
            Ref: PhraseBuildingModel
        StatusCode: 200
      - ResponseModels:
          application/json: Empty
        StatusCode: 404
Outputs:
  ApiId:
    Value:
      Ref: PhraseBuildingRestApi

